### PR TITLE
fix store bugs and add integer validation for mod-manager

### LINKED ISSUE #108: fix store bugs and add integer validation for mod-manager

### PR DESCRIPTION
**Pull request by jakehein**
Closes #108

### CODE REVIEW

File: src/app/components/store-list/store-list.component.ts [hunk 1]
```diff
@@ -30,7 +30,8 @@ export class StoreListComponent implements OnInit {
         && !this.isCurrentStoreDuplicateName
         && this.currentStore.cost > 0
         && this.currentStore.items.length > 0
-        && this.currentStore.items.every(c => !!c.itemType && c.quantity > 0);
+        && this.currentStore.items.every(c => !!c.itemType && c.quantity > 0)
+        && this.currentStore.cost.toString().includes('.');//isNan(this.currentStore.cost);
```
Comment (seiyria) [inline src/app/components/store-list/store-list.component.ts:34]: remove the comment here
